plugins {
    id 'com.gradleup.shadow' version '8.3.6'
}

architectury {
    platformSetupLoomIde()
    forge()
}

loom {
    forge {
        mixinConfig "projectcell.mixins.json"
    }
    runs {
        client {
            client()
            name "Forge Client"
            runDir "run/client"
            programArgs "--username", "Player1"
        }
        server {
            server()
            name "Forge Server"
            runDir "run/server"
        }
    }
}

repositories {
    mavenCentral()
    maven { url "https://cursemaven.com" }
}

tasks.named('processResources', ProcessResources).configure {
    def replaceProperties = [
        minecraft_version       : minecraft_version,
        minecraft_version_range : '[1.20.1,1.21)',
        forge_version           : project.forge_version,
        forge_version_range     : '[47,48)',
        loader_version_range    : '[47,)',
        mod_id                  : 'projectcell',
        mod_name                : 'ProjectCell Reforked',
        mod_version             : project.version,
        mod_authors             : 'gmr',
        mod_license             : 'MIT',
        mod_description         : '''An AE2 storage cell addon that bridges ProjectE with Applied Energistics 2.
EMC Storage Cell exposes the player\'s ProjectE transmutation knowledge and EMC balance as an AE2 storage cell.'''
    ]

    inputs.properties replaceProperties

    filesMatching(['META-INF/mods.toml']) {
        expand replaceProperties
    }
}

dependencies {
    forge "net.minecraftforge:forge:${minecraft_version}-${forge_version}"

    modImplementation("curse.maven:applied-energistics-2-223794:7148487")
    modImplementation("curse.maven:projecte-226410:4901949")
    modImplementation("curse.maven:guideme-1173950:8204776")

    modRuntimeOnly "curse.maven:jei-238222:8677648"
    modRuntimeOnly "curse.maven:project-expansion-579177:7247734"
}
